const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {JSDOM} = require('jsdom');
const html = fs.readFileSync(require('node:path').join(__dirname, '../dist/drawing-editor.html'), 'utf8');
const document = new JSDOM(html).window.document;
const section = (start,end) => html.slice(html.indexOf(start),html.indexOf(end,html.indexOf(start)));
assert.ok(document.querySelector('#aiTranslations'), 'translation list exists');
assert.ok(!/\.ai-note \.sticky-drag-handle\s*\{[^}]*background\s*:/.test(html),'translation drag handles remain invisible over original drawings');
assert.ok(/\.sticky-note\.ai-note\s*\{[^}]*background\s*:\s*transparent/.test(html),'translation stickers keep transparent background');
assert.ok(html.indexOf('id="aiFailures"') < html.indexOf('id="aiTranslations"') && html.indexOf('id="aiTranslations"') < html.indexOf('<main>'), 'list is directly above relocated toolbar');
assert.ok(document.querySelector('#undoBtn').closest('.header-actions') && document.querySelector('#redoBtn').closest('.header-actions'), 'history controls in header');
const note = {id:'ai-long-id',text:'完整譯文'.repeat(100),sourceText:'原始文字'.repeat(100),aiStatus:'draft',x:20,y:20,w:40,h:20,fontSize:6};
const page = notes => ({stickyNotes:notes,status:'pending',rotation:0,bakedRects:[],pendingRects:[],origW:900,origH:600,originalImageData:{}});
const file = {name:'synthetic.pdf',pages:[page([note,{id:'manual',text:'手動',x:2,y:2,w:20,h:10,fontSize:6}]),page([{...note,id:'page-two',text:'第二頁譯文'}])],pageIndex:0,history:[],future:[],marked:true};
const ctx = vm.createContext({translationSelection:null,adjustColorRuns:()=>{},colorSegments:n=>[{text:n.text,color:'#e03024'}],document,state:{files:[file],currentIndex:0},stickyLayer:document.getElementById('stickyLayer'),aiTranslations:document.getElementById('aiTranslations'),aiTranslationsList:document.getElementById('aiTranslationsList'),selectedNoteId:null,busy:false,restoring:false,zoom:1,progressMessage:{},pageEditKeys:['status','rotation','bakedRects','pendingRects','stickyNotes'],pageRuntimeKeys:['origW','origH','originalImageData'],editorLogicalSize:()=>({width:900,height:600}),scaleStickyLayer:()=>{},fitStickyNoteToText:()=>{},keepStickyNoteInBounds:()=>{},positionStickyElement:()=>{},renderFileList:()=>{},updateButtons:()=>{},selectFile:async(_,i)=>{file.pageIndex=i;ctx.renderStickyNotes();},noteNeedsReview:()=>false});
vm.runInContext(section('function attachPageAccessors(', 'function refreshEditor(')+section('function selectStickyNote(', 'function adjustSelectedNoteFont(')+section('function renderTranslationList()', 'function renderStickyNotes()')+section('function renderStickyNotes()', '// The rectangle body'),ctx);
ctx.editorToolbar=document.querySelector('.toolbar');ctx.fileInput=document.getElementById('fileInput');
vm.runInContext(section('function setBusy(', 'const pageEditKeys'),ctx);
ctx.attachPageAccessors(file);
ctx.renderFileList=()=>ctx.renderTranslationList();
ctx.renderStickyNotes();
const rows = () => [...document.querySelectorAll('#aiTranslationsList .ai-translation-row')];
assert.equal(rows().length,2);
assert.equal(rows()[0].querySelector('.ai-source').textContent,note.sourceText);
assert.equal(rows()[0].querySelector('.ai-translation').textContent,note.text);
assert.match(rows()[1].textContent,/第 2 頁/);
assert.equal(ctx.stickyLayer.querySelector('.ai-controls'),null,'no hover controls on note');
assert.equal(ctx.stickyLayer.querySelectorAll('.ai-note .sticky-resize').length,4);
ctx.setBusy(true);assert.equal(rows()[0].querySelector('.ai-delete').disabled,true);
ctx.setBusy(false);assert.equal(rows()[0].querySelector('.ai-delete').disabled,false,'buttons re-enable after loading');
(async()=>{
file.pages[1].originalImageData=null;
assert.equal(rows()[1].querySelector('.ai-retain'),null,'successful translation rows only expose delete');
assert.equal(file.pages[1].stickyNotes[0].aiStatus,'draft');
file.pages[1].originalImageData={};
rows()[1].click(); await new Promise(resolve=>setTimeout(resolve,0));
 assert.equal(file.pageIndex,1);assert.equal(ctx.selectedNoteId,'page-two');
 assert.equal(ctx.stickyLayer.querySelector('[data-note-id="page-two"]').classList.contains('selected'),true,'list row reveals under-sticker delete');
 assert.equal(ctx.stickyLayer.querySelector('[data-note-id="page-two"] .ai-note-delete').textContent,'×');
 await ctx.selectFile(0,0);
 assert.equal(rows()[0].querySelector('.ai-retain'),null);
 note.aiStatus='confirmed';file.marked=false;
 const text=ctx.stickyLayer.querySelector('.ai-note textarea');text.value+='校對';text.dispatchEvent(new document.defaultView.Event('input'));
 assert.equal(note.aiStatus,'confirmed','text editing preserves confirmation');
 assert.equal(rows()[0].querySelector('.ai-translation').textContent,note.text);
 const restored={...note,id:'ai-long-id',text:note.text,aiStatus:'confirmed'};
 file.stickyNotes[0]=restored;
 text.value+='再編';text.dispatchEvent(new document.defaultView.Event('input'));
 assert.equal(restored.text,text.value,'stale textarea updates canonical note by stable ID');
 assert.equal(restored.aiStatus,'confirmed','canonical confirmation survives a stale textarea');
 assert.equal(rows()[0].querySelector('.ai-retain'),null,'list never reintroduces per-note retain');
 rows()[0].querySelector('.ai-delete').click();assert.equal(file.stickyNotes.length,1);assert.equal(file.stickyNotes[0].id,'manual');assert.equal(rows().length,1);
 console.log('PASS: translation list location, full text, navigation, retain/edit/delete, manual preservation');
})().catch(e=>{console.error(e);process.exitCode=1});
