const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const root = path.join(__dirname,'../dist');
const html = fs.readFileSync(path.join(root,'drawing-editor.html'),'utf8');
const dom = new JSDOM(html);
const scripts = [...dom.window.document.querySelectorAll('script')];
assert.equal(scripts.length, 5);
for (const script of scripts) {
 if (script.src) assert.ok(fs.existsSync(path.join(root,script.getAttribute('src'))), `Missing ${script.src}`);
 else new vm.Script(script.type === 'module' ? script.textContent.replace(/^import .*?;\s*$/gm,'') : script.textContent);
}
assert.match(html,/drawing-desk-independent-editor-v11-progress/);
assert.match(html,/isEvalSupported: false/g);
assert.doesNotMatch(html, /https:\/\/(?:cdnjs|fonts\.googleapis)/);
assert.match(html,/if \(!window\.confirm\(/);
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
assert.match(app,/\['drawing-workspace'[^\n]*\['drawing-editor'/);
assert.match(app,/'drawing-editor':casesPage/);
const ui = fs.readFileSync(path.join(root,'antd-ui.js'),'utf8');
assert.match(ui,/drawing-editor\.html/);
const component=fs.readFileSync(path.join(__dirname,'../src/ui/main.jsx'),'utf8');
const editor=component.slice(component.indexOf('function IndependentDrawingEditor('),component.indexOf('function DrawingWorkspace('));
assert.doesNotMatch(editor,/獨立作業區|獨立編輯 PDF|上傳 PDF 後可加入/);
for(const id of ['clearProgressBtn','saveProgressBtn','exportBtn']) assert.ok(editor.includes(id));
assert.match(html,/document\.querySelector\('main'\)\.before\(editorToolbar\)/);
assert.match(html,/editorToolbar\.hidden = false/);
assert.match(html,/bctx\.fillStyle = '#fff'/);
assert.ok(html.includes('`${base}_NL.pdf`'));
assert.match(html,/if \(!window\.confirm\(`PDF 已完成/);
assert.match(html,/exportIndependentPDF\(file\.arrayBuffer\.slice\(0\),edits\)/);
assert.doesNotMatch(html,/<h1>圖面編輯工具<\/h1>/);
assert.match(html,/header \{ display:none; \}/);
assert.match(html,/const requiredWidth = Math\.ceil\(edit\.origW \* zoom \* \(window\.devicePixelRatio \|\| 1\)\)/);
assert.match(html,/scheduleEditorRender\(\)/);
assert.match(html,/previewPixelWidth\(sheet\)/);
assert.doesNotMatch(html,/scale: 1200 \/ page\.getViewport/);
assert.match(html,/const \{width,height\} = editorLogicalSize\(state\.files\[state\.currentIndex\]\)/);
const toolbar=dom.window.document.querySelector('.toolbar');
const labels=Object.fromEntries([...toolbar.querySelectorAll('button[id]')].map(button=>[button.id,button.textContent.trim()]));
assert.equal(labels.undoBtn,'復原');
assert.equal(labels.redoBtn,'重做');
assert.equal(labels.batchBtn,'批次遮蓋（套用檔內）');
assert.equal(labels.batchOtherBtn,'批次遮蓋（套用餘檔首頁）');
const addNote=toolbar.querySelector('#addNoteBtn').closest('.note-menu-wrap');
assert.equal(addNote.nextElementSibling.id,'fontGrowBtn');
assert.equal(addNote.nextElementSibling.nextElementSibling.id,'fontShrinkBtn');
assert.equal(addNote.nextElementSibling.disabled,true);
assert.equal(addNote.nextElementSibling.nextElementSibling.disabled,true);
assert.match(html,/fontSize:\s*6\s*\/\s*zoom/);
assert.match(html,/padding:\s*3\s*\/\s*zoom/);
assert.match(html,/notePaddingVersion:\s*2/);
assert.match(html,/migrateNotePadding\(saved\)/);
assert.match(html,/file\.restoredOriginal = true/);
assert.match(html,/file\.marked \|\| file\.restoredOriginal/);
assert.match(html,/remove\.className = 'mask-delete'/);
assert.match(html,/note\.h = note\.manualH/);
assert.match(html,/Math\.max\(4, action\.w/);
assert.match(html,/Math\.max\(4, action\.h/);
assert.match(html,/batchOtherBtn\.onclick/);
assert.match(html,/visualLines:\s*wrapStickyText/);
console.log('PASS: independent editor route, toolbar controls, default note size and adaptive PDF rasterization');
