const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const root = path.join(__dirname,'../dist');
const html = fs.readFileSync(path.join(root,'drawing-editor.html'),'utf8');
const dom = new JSDOM(html);
const scripts = [...dom.window.document.querySelectorAll('script')];
assert.equal(scripts.length, 5);
for (const script of scripts) {
 if (script.src) assert.ok(fs.existsSync(path.join(root,script.getAttribute('src'))), `Missing ${script.src}`);
 else new vm.Script(script.type === 'module' ? script.textContent.replace(/^import .*?;\s*$/gm,'') : script.textContent);
}
assert.match(html,/drawing-desk-independent-editor-v11-progress/);
assert.match(html,/isEvalSupported: false/g);
assert.doesNotMatch(html, /https:\/\/(?:cdnjs|fonts\.googleapis)/);
assert.match(html,/if \(!window\.confirm\(/);
const ui = fs.readFileSync(path.join(root,'antd-ui.js'),'utf8');
assert.match(ui,/drawing-editor\.html/);
const component=fs.readFileSync(path.join(__dirname,'../src/ui/main.jsx'),'utf8');
for(const id of ['undoBtn','redoBtn','clearProgressBtn','previewBtn','saveProgressBtn','exportBtn']) assert.ok(component.includes(id));
assert.match(component,/MutationObserver\(sync\)/);
assert.match(component,/onClick=\{\(\)=>forward\('undoBtn'\)\}>復原<\/Button>/);
assert.match(component,/onClick=\{\(\)=>forward\('redoBtn'\)\}>重做<\/Button>/);
assert.match(html,/document\.querySelector\('main'\)\.before\(editorToolbar\)/);
assert.match(html,/editorToolbar\.hidden = false/);
assert.match(html,/bctx\.fillStyle = '#fff'/);
assert.ok(html.includes('`${base}_NL.pdf`'));
assert.match(html,/if \(!window\.confirm\(`PDF 已完成/);
assert.match(html,/exportIndependentPDF\(file\.arrayBuffer\.slice\(0\),edits\)/);
assert.doesNotMatch(html,/<h1>圖面編輯工具<\/h1>/);
assert.match(html,/header \{ display:none; \}/);
assert.match(html,/const requiredWidth = Math\.ceil\(edit\.origW \* zoom \* \(window\.devicePixelRatio \|\| 1\)\)/);
assert.match(html,/scheduleEditorRender\(\)/);
assert.match(html,/previewPixelWidth\(sheet\)/);
assert.doesNotMatch(html,/scale: 1200 \/ page\.getViewport/);
assert.match(html,/const \{width,height\} = editorLogicalSize\(state\.files\[state\.currentIndex\]\)/);
const toolbar=dom.window.document.querySelector('.toolbar');
const labels=Object.fromEntries([...toolbar.querySelectorAll('button[id]')].map(button=>[button.id,button.textContent.trim()]));
const headerActions=dom.window.document.querySelector('.header-actions');
assert.equal(headerActions.querySelector('#undoBtn').textContent,'復原');
assert.equal(headerActions.querySelector('#redoBtn').textContent,'重做');
assert.equal(headerActions.querySelector('#redoBtn').nextElementSibling.id,'clearProgressBtn');
assert.equal(headerActions.querySelector('#previewBtn').textContent,'預覽本檔完工圖');
assert.equal(headerActions.querySelector('#previewBtn').nextElementSibling.id,'saveProgressBtn');
assert.equal(toolbar.querySelector('#previewBtn'),null);
assert.equal(labels.batchBtn,'批次遮蓋（套用檔內）');
assert.equal(labels.batchOtherBtn,'批次遮蓋（套用餘檔首頁）');
const addNote=toolbar.querySelector('#addNoteBtn').closest('.note-menu-wrap');
assert.equal(addNote.nextElementSibling.id,'batchStickyFileBtn');
assert.equal(addNote.nextElementSibling.nextElementSibling.id,'batchStickyOtherBtn');
assert.equal(addNote.nextElementSibling.nextElementSibling.nextElementSibling.id,'fontGrowBtn');
assert.equal(labels.batchStickyFileBtn,'批次處理便利貼（套用檔內）');
assert.equal(labels.batchStickyOtherBtn,'批次處理便利貼（套用餘檔首頁）');
assert.equal(addNote.nextElementSibling.disabled,true);
assert.equal(addNote.nextElementSibling.nextElementSibling.disabled,true);
assert.match(html,/fontSize:\s*6\s*\/\s*zoom/);
assert.match(html,/padding:\s*3\s*\/\s*zoom/);
assert.match(html,/notePaddingVersion:\s*2/);
assert.match(html,/migrateNotePadding\(saved\)/);
assert.match(html,/file\.restoredOriginal = true/);
assert.match(html,/file\.marked \|\| file\.restoredOriginal/);
assert.match(html,/remove\.className = 'mask-delete'/);
assert.match(html,/note\.h = note\.manualH/);
assert.match(html,/Math\.max\(4, action\.w/);
assert.match(html,/Math\.max\(4, action\.h/);
assert.match(html,/batchOtherBtn\.onclick/);
assert.match(html,/batchBtn\.disabled = !ready \|\| file\.pendingRects\.length === 0/);
assert.match(html,/const areas = source\.pendingRects\.map/);
assert.match(html,/function stickyVisualLayout\(note, textarea\)/);
assert.match(html,/function scaleStickyLayer\(width, height\)/);
assert.match(html,/stickyLayer\.style\.transform = `scale\(\$\{zoom\}\)`/);
assert.match(html,/text\.style\.fontSize = note\.fontSize \+ 'px'/);
assert.match(html,/const availableWidth = note\.w - note\.padding \* 2/);
assert.match(html,/const width = Math\.max\(1, note\.w - note\.padding \* 2\)/);
assert.match(html,/if \(rebuildNotes\) renderStickyNotes\(\);\s*else scaleStickyLayer/);
assert.match(html,/zoomInBtn\.onclick = \(\) => \{[^\n]*applyZoom\(false\)/);
assert.match(html,/zoomOutBtn\.onclick = \(\) => \{[^\n]*applyZoom\(false\)/);
assert.match(html,/function zoomAt\([\s\S]*?applyZoom\(false\)/);
assert.match(html,/visualLines: lines, visualWidths: widths/);
assert.equal(labels.aiTranslateBtn,'翻譯本檔全部頁面');
assert.equal(labels.aiRetainPageBtn,'保留本頁所有翻譯');
assert.equal(labels.aiDeletePageBtn,'刪除本頁所有翻譯');
assert.equal(labels.addTranslationBtn,'新增翻譯貼紙');
assert.equal(toolbar.querySelector('#aiTranslateBtn').nextElementSibling.id,'addTranslationBtn');
assert.equal(toolbar.querySelector('#addTranslationBtn').nextElementSibling.id,'aiRetainPageBtn');
assert.equal(toolbar.querySelector('#aiRetainPageBtn').nextElementSibling.id,'aiDeletePageBtn');
assert.equal(dom.window.document.getElementById('aiGlossaryBtn'),null);
assert.equal(dom.window.document.getElementById('aiGlossary'),null);
assert.match(html,/import \{[^}]*sourceCandidates[^}]*mergeDrafts[^}]*\} from '\.\/independent-ai-overlay\.js'/);
assert.match(html,/aiPost\('\/api\/ai\/ocr'/);
assert.match(html,/translateInBatches\(items,\{\},aiPost/);
assert.match(html,/localStorage\.removeItem\(GLOSSARY_KEY\)/);
assert.match(html,/getTextContent\(/);
assert.match(html,/note\.aiStatus==='confirmed'/);
assert.match(html,/exportableNotes\(page\.stickyNotes\)/);
assert.doesNotMatch(html,/\.sticky-note:hover \.ai-controls|\.sticky-note:focus-within \.ai-controls/);
assert.doesNotMatch(html,/element\.querySelector\('\.ai-confirmed'\)\?\.classList\.remove\('ai-confirmed'\)/);
assert.match(html,/note\.aiWarning/,'unverified terminology warning must be visible on each note');
assert.match(html,/\.ai-note[^}]*background/);
assert.match(html,/batchStickyFileBtn\.disabled = !selected \|\| !!selected\.aiStatus \|\| file\.pages\.length < 2/);
assert.match(html,/batchStickyOtherBtn\.disabled = !selected \|\| !!selected\.aiStatus \|\| state\.files\.length < 2/);
assert.match(html,/batchStickyFileBtn\.onclick=\(\)=>copySelectedStickyNotes\('file'\)/);
assert.match(html,/batchStickyOtherBtn\.onclick=\(\)=>copySelectedStickyNotes\('other-first-pages'\)/);
assert.match(html,/\.mask-delete,\.sticky-delete,\.ai-note-delete\s*\{[^}]*top:-10px; right:-10px;[^}]*width:20px; height:20px/);
assert.match(html,/removeTranslation\.textContent='×'/);
assert.match(html,/\.ai-note \.ai-note-delete \{ display:none; \}/);
assert.match(html,/\.ai-note\.selected \.ai-note-delete \{ display:flex; \}/);
assert.doesNotMatch(html,/deleteButtonBaseW|deleteButtonBaseH|removeTranslation\.style\.fontSize/);
console.log('PASS: independent editor controls, batch notes, delete icons and adaptive PDF rasterization');
